### ISSUE TITLE
Error on running "InferAncestralStates" program of SiFit.

### ISSUE THREAD

**Issue by AkankshaFarswan** [KChen-lab/SiFit#3]
I am getting an error on running "InferAncestralStates" program of SiFit.
I used the following commands-
1) java -cp SiFit.jar SiFit.algorithm.InferAncestralStates
2) java -cp SiFit.jar SiFit.algorithm.InferAncestralStates -m 20 -n 446 -fp 0.002 -fn 0.2 -iter 10000 -df 1 -ipMat exampleFiles/dataset_20cells.txt
I got the same error for both the commands. 

 Exception in thread "main" java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at SiFit.io.VariantMatrixReader.populateVarGTMatrix(VariantMatrixReader.java:38)
	at SiFit.algorithm.InferAncestralStates.annotateMutations(InferAncestralStates.java:391)
	at SiFit.algorithm.InferAncestralStates.main(InferAncestralStates.java:501)

**Comment by lshh125** [comment]
Would you be able to check if you can provide the following arguments to it? The problem seems to be missing arguments. What you are using now is for inferring phylogeny, not the order of mutations. 

-fp <Double> Set to the false positive rate of the single-cell sequencing experiment.
-fn <Double> Set to the ML estimate of false negative rate reported by SiFit during learning the tree.
-w <Double> Set to the ML estimate of LOH rate reported by SiFit during learning.
-d <Double> Set to the ML estimate of deletion rate reported by SiFit during learning.
-df <Integer> Set to 0 if the input matrix is binary. Currently, we support only binary input matrix for this program.
-ipMat <filename> Replace with the path to the file containing the input genotype matrix.
-tree <filename> Replace with the path to the file containing the newick string format for the tree inferred by SiFit.
-cellNames <filename> Replace with the path to the file containing the names of the cells in the dataset. It should be a text file that has the names of the cells in a single line separated by whitespace, the cell names should match the leaf names of the tree, also should be in the same order as they appear in the input genotype matrix.
-geneNames <filename> Replace with the path to the file containing the names of the genes that are mutated. Each row of this test file should contain one gene name. The names of the genes should be in the same order as they appear in the input genotype matrix.
-expectedMatrix <filename> Replace output file where the expected genotype matrix will be written.

You would need to first use the "java -jar SiFit.jar -m 20 -n 446 -fp 0.002 -fn 0.2 -iter 10000 -df 1 -ipMat exampleFiles/dataset_20cells.txt", and have a look at the output txt for the best values of the parameters, and use them (and the output tree) for running "java -cp SiFit.jar SiFit.algorithm.InferAncestralStates".

Hope this helps.
